# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure(2) do |config|
  config.vm.box = "generic/centos8"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.define "rpm-test" do |v|
    v.vm.host_name = "rpm-test".to_s
    v.vm.provision "shell", path: "rpm_script.sh"
  end
end