ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
MACHINES = {
  # Указываем имя ВМ "kernel update"
  :"dynweb" => {
              #Какой vm box будем использовать
              :box_name => "ubuntu/20.04",
              :ip_addr => '192.168.56.111',
              #Указываем количество ядер ВМ
              :cpus => 1,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    config.vm.network "forwarded_port", guest: 8082, host: 8082
    config.vm.network "forwarded_port", guest: 8083, host: 8083
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = boxconfig[:memory]
        vb.cpus = boxconfig[:cpus]
        vb.customize ["modifyvm", :id, '--audio', 'none']
      end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "prov.yml"
      end
    end
  end
end

