# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"
VAGRANT_EXPERIMENTAL="disks"
'''
#unused
def create_sata(count)
    blocks = {}
    (1..count).each do |n|
      blocks["sata#{n}"] = "{:dfile => ./sata#{n}.vdi, :size => 250, :port => #{n}}"
    end
    blocks
end
'''
MACHINES = {
    :vmzfs => {
      :box_name => 'almalinux/9',
#      :box_version => "9.1.20221117",
      :cpus => 2,
      :memory => 1024,
#      :disks => create_sata(3)
    }
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.synced_folder ".", "/vagrant", disabled: true
        if Vagrant.has_plugin?("vagrant-vbguest") then
          config.vbguest.auto_update = false
        end
        config.vm.define boxname do |box1|
            box1.vm.box = boxconfig[:box_name]
#            box1.vm.box_version = boxconfig[:box_version]
            box1.vm.host_name = boxname.to_s
            box1.vm.provider "virtualbox" do |v|
                v.memory = boxconfig[:memory]
                v.cpus = boxconfig[:cpus]
                v.customize ["modifyvm", :id, "--audio", "none"]
            end
            (1..8).each do |i|
                box1.vm.disk :disk, size: "512MB", name: "sata#{i}"
            end
            box1.vm.provision "shell", path: "setup_zfs.sh"
        end
    end
end
